Resources:
  PrismixUserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/prismix-user-credentials
      Description: Prismix IAM User credentials for S3 access (${self:provider.stage})
      SecretString: !Sub |
        {
          "accessKeyId": ${env:AWS_ACCESS_KEY_ID},
          "secretAccessKey": ${env:AWS_SECRET_ACCESS_KEY}
        } 