# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: prismix
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: prismix
service: prismix-serverless

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: ${self:custom.memorySize.${self:provider.stage}}
  environment:
    ENVIRONMENT: ${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      level: ERROR # or INFO
      fullExecutionData: true
  apiGateway:
    shouldStartNameWithService: true

custom:
  memorySize:
    prod: 256
    dev: 128

functions:
  main:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-UserPool
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-UserPoolClient
        UserPoolId: 
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    PrismixImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-prismix-image-bucket-${aws:accountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: 
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]

    CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        RoleName: ${self:service}-${self:provider.stage}-CloudWatchRole

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties:
        CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  Outputs:
    UserPoolId:
      Description: Cognito User Pool ID
      Value: 
        Ref: CognitoUserPool
    UserPoolClientId:
      Description: Cognito User Pool Client ID
      Value: 
        Ref: CognitoUserPoolClient
    S3BucketName:
      Description: S3 Bucket Name
      Value: 
        Ref: PrismixImageBucket