# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: prismix
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: prismix
service: prismix-serverless

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

# custom:
#   serverless-offline:
#     httpPort: 3000  # Change this to modify the API port
#     lambdaPort: 3002  # Change this to modify the Lambda emulation port

functions:
  handler:
    handler: src/handlers/example.hello
    events:
      - http:
          path: /
          method: get

