# Service Definition
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: prismix
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: prismix
service: prismix-serverless

plugins:
  - serverless-offline # for local development and testing
  - serverless-dotenv-plugin # for loading .env files

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: ${self:custom.memorySize.${self:provider.stage}}
  environment:
    ENVIRONMENT: ${self:provider.stage}
    PROJECTS_TABLE: ${self:service}-${self:provider.stage}-Projects
    JOBS_TABLE: ${self:service}-${self:provider.stage}-Jobs
    IMAGES_TABLE: ${self:service}-${self:provider.stage}-Images
    PROCESSED_RESULTS_TABLE: ${self:service}-${self:provider.stage}-ProcessedResults
    SQS_QUEUE_URL: 
      Ref: EligibleImageQueue
    DEAD_LETTER_QUEUE_URL:
      Ref: ImageDeadLetterQueue
  iam:
    role: BaseCloudWatchRole
  logs:
    # restApi:
      # accessLogging: true
      # executionLogging: true
      # level: INFO
      # fullExecutionData: true
    restApi: false
  apiGateway:
    shouldStartNameWithService: true
  tracing:
    apiGateway: true
    lambda: true
  stackTags:
    CLOUDFORMATION_DEBUG_LOG: true

# re-usable variables
custom:
  memorySize:
    prod: 256
    dev: 128
  bucketName: ${self:service}-${self:provider.stage}-bucket
  queueName: ${self:service}-${self:provider.stage}-queue
  # environment: ${file(.env.${self:provider.stage})}
  dotenv:
    path: .env.${self:provider.stage}
  deadLetterQueueName: ${self:service}-${self:provider.stage}-dlq

functions:
  main:
    handler: src/handlers/example.hello
    events:
      - http:
          path: /
          method: ANY
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer
          cors: true

  # Initial Check Function
  processImage:
    handler: src/handlers/processImage.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          existing: true
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
      SQS_QUEUE_URL: 
        Ref: EligibleImageQueue
    role: ProcessImageFunctionRole

  # Worker Function - main processing functions
  worker:
    handler: src/handlers/worker.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [EligibleImageQueue, Arn]
    environment:
      PROJECTS_TABLE: ${self:provider.environment.PROJECTS_TABLE}
      JOBS_TABLE: ${self:provider.environment.JOBS_TABLE}
      IMAGES_TABLE: ${self:provider.environment.IMAGES_TABLE}
      PROCESSED_RESULTS_TABLE: ${self:provider.environment.PROCESSED_RESULTS_TABLE}
    role: WorkerFunctionRole

  # Dead Letter Queue Processor
  deadLetterQueueProcessor:
    handler: src/handlers/deadLetterQueueProcessor.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ImageDeadLetterQueue, Arn]
    environment:
      PROJECTS_TABLE: ${self:provider.environment.PROJECTS_TABLE}
      JOBS_TABLE: ${self:provider.environment.JOBS_TABLE}
      IMAGES_TABLE: ${self:provider.environment.IMAGES_TABLE}
      PROCESSED_RESULTS_TABLE: ${self:provider.environment.PROCESSED_RESULTS_TABLE}
    role: DeadLetterQueueProcessorRole

resources:
  Resources:
    # Basic IAM Role - used by Lambda functions
    BaseCloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess

    # S3 & SQS access IAM Role - used by Lambda functions
    ProcessImageFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: s3-sqs-access-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource: 
                    - Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - ${self:custom.bucketName}
                        - "/*"
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    Fn::GetAtt: [EligibleImageQueue, Arn]

    # CloudWatch Write access Role - used by API Gateway
    IamRoleApiGatewayCloudWatchLogs:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

    # SQS & DynamoDB access Role - used by worker functions
    WorkerFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: dynamodb-sqs-access-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                  Resource: 
                    - Fn::GetAtt: [ProjectsTable, Arn]
                    - Fn::GetAtt: [JobsTable, Arn]
                    - Fn::GetAtt: [ImagesTable, Arn]
                    - Fn::GetAtt: [ProcessedResultsTable, Arn]
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                  Resource:
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ProjectsTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [JobsTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ImagesTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ProcessedResultsTable, Arn]
                        - "/index/*"
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    Fn::GetAtt: [EligibleImageQueue, Arn]

    # SQS & DynamoDB access Role - used by deadLetterQueueProcessor functions
    DeadLetterQueueProcessorRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: dlq-dynamodb-access-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                  Resource: 
                    - Fn::GetAtt: [ProjectsTable, Arn]
                    - Fn::GetAtt: [JobsTable, Arn]
                    - Fn::GetAtt: [ImagesTable, Arn]
                    - Fn::GetAtt: [ProcessedResultsTable, Arn]
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                  Resource:
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ProjectsTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [JobsTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ImagesTable, Arn]
                        - "/index/*"
                    - Fn::Join:
                      - ""
                      - - Fn::GetAtt: [ProcessedResultsTable, Arn]
                        - "/index/*"
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    Fn::GetAtt: [ImageDeadLetterQueue, Arn]

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      DependsOn: IamRoleApiGatewayCloudWatchLogs
      Properties:
        CloudWatchRoleArn: 
          Fn::GetAtt: [IamRoleApiGatewayCloudWatchLogs, Arn]

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-UserPool
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-UserPoolClient
        UserPoolId: 
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    PrismixImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: 
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]

    EligibleImageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [ImageDeadLetterQueue, Arn]
          maxReceiveCount: 3

    ImageDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.deadLetterQueueName}

    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-Projects
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ProjectId
            AttributeType: S
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: ProjectId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserProjectIndex
            KeySchema:
              - AttributeName: UserId
                KeyType: HASH
              - AttributeName: ProjectId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-Jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: JobId
            AttributeType: S
          - AttributeName: ProjectId
            AttributeType: S
        KeySchema:
          - AttributeName: JobId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ProjectJobIndex
            KeySchema:
              - AttributeName: ProjectId
                KeyType: HASH
              - AttributeName: JobId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    ImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-Images
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ImageId
            AttributeType: S
          - AttributeName: JobId
            AttributeType: S
        KeySchema:
          - AttributeName: ImageId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: JobImageIndex
            KeySchema:
              - AttributeName: JobId
                KeyType: HASH
              - AttributeName: ImageId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    ProcessedResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-ProcessedResults
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ResultId
            AttributeType: S
          - AttributeName: ImageId
            AttributeType: S
        KeySchema:
          - AttributeName: ResultId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ImageResultIndex
            KeySchema:
              - AttributeName: ImageId
                KeyType: HASH
              - AttributeName: ResultId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    UserPoolId:
      Description: Cognito User Pool ID
      Value: 
        Ref: CognitoUserPool
    UserPoolClientId:
      Description: Cognito User Pool Client ID
      Value: 
        Ref: CognitoUserPoolClient
    S3BucketName:
      Description: User uploaded images
      Value: 
        Ref: PrismixImageBucket
    ProjectsTableName:
      Description: DynamoDB Projects Table Name
      Value: 
        Ref: ProjectsTable
    ProjectsTableArn:
      Description: DynamoDB Projects Table ARN
      Value:
        Fn::GetAtt: [ProjectsTable, Arn]
    JobsTableName:
      Description: DynamoDB Jobs Table Name
      Value: 
        Ref: JobsTable
    JobsTableArn:
      Description: DynamoDB Jobs Table ARN
      Value:
        Fn::GetAtt: [JobsTable, Arn]
    ImagesTableName:
      Description: DynamoDB Images Table Name
      Value: 
        Ref: ImagesTable
    ImagesTableArn:
      Description: DynamoDB Images Table ARN
      Value:
        Fn::GetAtt: [ImagesTable, Arn]
    ProcessedResultsTableName:
      Description: DynamoDB Processed Results Table Name
      Value: 
        Ref: ProcessedResultsTable
    ProcessedResultsTableArn:
      Description: DynamoDB Processed Results Table ARN
      Value:
        Fn::GetAtt: [ProcessedResultsTable, Arn]
    SQSQueueUrl:
      Description: SQS Queue URL
      Value:
        Ref: EligibleImageQueue
    SQSQueueArn:
      Description: SQS Queue ARN
      Value:
        Fn::GetAtt: [EligibleImageQueue, Arn]
    DeadLetterQueueUrl:
      Description: Dead Letter Queue URL
      Value:
        Ref: ImageDeadLetterQueue
    DeadLetterQueueArn:
      Description: Dead Letter Queue ARN
      Value:
        Fn::GetAtt: [ImageDeadLetterQueue, Arn]