# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: prismix
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: prismix
service: prismix-serverless

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: ${self:custom.memorySize.${self:provider.stage}}
  environment:
    ENVIRONMENT: ${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-DefaultExecutionRole
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:${self:provider.region}:*:*"
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      level: INFO
      fullExecutionData: true
  apiGateway:
    shouldStartNameWithService: true

custom:
  memorySize:
    prod: 256
    dev: 128

functions:
  main:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer
          cors: true

  processImage:
    handler: src/handlers/processImage.handler
    events:
      - http:
          path: /process-image
          method: POST
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer
    environment:
      BUCKET_NAME: ${self:resources.Resources.PrismixImageBucket.Properties.BucketName}
      SQS_QUEUE_URL: 
        Ref: MySQSQueue
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: 
          - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: PrismixImageBucket
              - "/*"
      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource:
          Fn::GetAtt: [MySQSQueue, Arn]

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-UserPool
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-UserPoolClient
        UserPoolId: 
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    PrismixImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.stage}-prismix-image-bucket-${aws:accountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: 
          Ref: ApiGatewayRestApi
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]

    MySQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-my-queue

    ApiGatewayAccount:
      Type: AWS::ApiGateway::Account
      Properties:
        CloudWatchRoleArn: 
          Fn::GetAtt: [IamRoleApiGatewayCloudWatchLogs, Arn]

    IamRoleApiGatewayCloudWatchLogs:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
        Path: "/"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  Outputs:
    UserPoolId:
      Description: Cognito User Pool ID
      Value: 
        Ref: CognitoUserPool
    UserPoolClientId:
      Description: Cognito User Pool Client ID
      Value: 
        Ref: CognitoUserPoolClient
    S3BucketName:
      Description: S3 Bucket Name
      Value: 
        Ref: PrismixImageBucket